version: '3'
services:
  prediccion:
    image: prediccion:v1
    build: .
    container_name: prediccion
    restart: unless-stopped
    ports:
      - "8052:8052"
    networks:
      - deteccion-anomalias
networks:
  deteccion-anomalias:
    external: true